Delete metabolite
cnapy-org/CNApy pull request #358
Opened 2022-01-12 14:57 UTC by axelvonkamp

2022-01-13 09:01 UTC, axelvonkamp commented
Oh , right. I also noticed that the equations in the tool tips of the reaction boxes aren't update either.

2022-01-15 00:46 UTC, sthiele requested changes

2022-01-15 07:22 UTC, sthiele approved these changes

2022-01-15 16:38 UTC, axelvonkamp commented on cnapy/gui_elements/metabolite_list.py
> +        self.metaboliteDeleted.emit(self.metabolite, affected_reactions)
Yes, that was the original plan, but after self.metabolite.remove_from_model() the frozen set metabolite.reactions is empty. So I now remember the set before metabolite removal and pass it as separate parameter to handle_changed_metabolite.

2022-01-15 18:42 UTC, sthiele commented on cnapy/gui_elements/metabolite_list.py
> +        self.metaboliteDeleted.emit(self.metabolite, affected_reactions)
I see.

2022-01-17 09:23 UTC, merged