an altenative objective function can be part of a scenario and saved
cnapy-org/CNApy pull request #388
Opened 2022-07-27 09:15 UTC by axelvonkamp

scenario saves also the pinned reactions and a description
objective tab for editing/switching the objective functions
some glitches and bugs fixed

2022-08-01 12:33 UTC, Paulocracy requested changes
Thank you for the expanded scenario handling :-)
Generally, the objective override and description works great for me, I just encountered the following (partly subjective) issues:
* I didn't find a way to de-pin the scenario-edited reactions, is there a simple way to do it? Otherwise, maybe a toggle button (such as for the scenario coloring) might be useful UI-wise.
* The "Scenario" menu entry is now quite overwhelming :O Maybe we could discuss if there's a way to sort the entries, and which entries should be included there. E.g., loading and saving a scenario is not put in a subsequent order and "Show model bounds" could be moved somewhere else.

2022-08-01 12:57 UTC, axelvonkamp commented
>     * I didn't find a way to de-pin the scenario-edited reactions, is there a simple way to do it? Otherwise, maybe a toggle button (such as for the scenario coloring) might be useful UI-wise.

You can unpin a reaction via the context menu associated with the reaction row in the reaction list. Or do you want to unpin multiple reactions?
 
>     * The "Scenario" menu entry is now quite overwhelming :O Maybe we could discuss if there's a way to sort the entries, and which entries should be included there. E.g., loading and saving a scenario is not put in a subsequent order and "Show model bounds" could be moved somewhere else.

Yes, it looks a bit overwhelming, if you want to rearrange it go ahead :-)

2022-08-01 13:40 UTC, Paulocracy commented
Yes I meant multiple or just all pinned reactions at once.
And I'll add a proposal for a menu entry change.

2022-08-01 14:25 UTC, axelvonkamp commented
> Yes I meant multiple or just all pinned reactions at once. And I'll add a proposal for a menu entry change.

Multiple selections in the reaction list are currently not supported so I made a new menu entry for unpinning all reactions.

2022-08-01 16:35 UTC, sthiele commented on cnapy/appdata.py
> +        # self.scen_values: Dict[str, Tuple[float, float]] = {}
You can get rid of this line.

2022-08-02 11:17 UTC, Paulocracy commented on cnapy/appdata.py
> +        # self.scen_values: Dict[str, Tuple[float, float]] = {}
Done by @axelvonkamp

2022-08-03 09:09 UTC, Paulocracy approved these changes
Thank you for all changes and improvements :-)

2022-08-03 09:20 UTC, merged